[build]
  publish = "." # Root folder where index.html is located
  command = "" # No build command needed for plain HTML/JS/CSS

[functions]
  directory = "netlify/functions" # Folder where form-submit.js is located

[[headers]]
  for = "/.netlify/functions/form-submit" # Apply headers only to your function's endpoint
  [headers.values]
    Access-Control-Allow-Origin = "*" # Allow requests from all origins
    Access-Control-Allow-Methods = "POST, OPTIONS" # Supported methods
    Access-Control-Allow-Headers = "Content-Type" # Allow content-type header for JSON requests

[[redirects]]
  from = "/form-submit" # Match the endpoint used in your client-side JavaScript
  to = "/.netlify/functions/form-submit" # Points to your Netlify Function
  status = 200 # HTTP OK
  force = true # Force the redirect, ensuring it's not cached elsewhere
