[build]
  publish = "."  # The root folder where your index.html file is
  command = ""    # No build command needed for plain HTML/JS/CSS

[functions]
  directory = "netlify/functions"  # Folder where your form-submit.js is

[[headers]]
  for = "/.netlify/functions/form-submit"
  [headers.values]
    Access-Control-Allow-Origin = "*"  # Allow any origin for CORS
    Access-Control-Allow-Methods = "POST, OPTIONS"  # Allow POST and OPTIONS methods
    Access-Control-Allow-Headers = "Content-Type"  # Allow the Content-Type header for POST requests

[[redirects]]
  from = "/form-submit"  # Matching client-side endpoint
  to = "/.netlify/functions/form-submit"  # Points to Netlify function
  status = 200           # OK status
  force = true           # Ensures that the redirect is applied
