[build]
  publish = "." # Publish the root folder where index.html is located
  command = "" # Leave this empty since no build command is needed for plain HTML/JS/CSS

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" # Allow all origins; adjust based on security needs
    Access-Control-Allow-Methods = "POST, OPTIONS" # Methods allowed for serverless functions
    Access-Control-Allow-Headers = "Content-Type" # Allow content-type header

[[redirects]]
  from = "/api/handle-login"
  to = "/api/form-submit"
  status = 200
  force = true

[[redirects]]
  from = "/api/handle-registration"
  to = "/api/form-submit"
  status = 200
  force = true
